### ISSUE TITLE
Generate Content with JSON response schema

### ISSUE THREAD

**Issue by fdelbrayelle** [kestra-io/plugin-gemini#3]
### Feature description

As an additional feature for this plugin, it could be interesting to be able to [format the response with a JSON schema (official Java lib doc)](https://github.com/googleapis/java-genai/?tab=readme-ov-file#generate-content-with-json-response-schema).

Example of YAML flow:

```yaml
id: gemini_text_completion
namespace: company.team

tasks:
  - id: text_completion
    type: io.kestra.plugin.gemini.TextCompletion
    apiKey: ${{ secrets.GEMINI_API_KEY }}
    model: "gemini-2.5-flash-preview-05-20"
    prompt: What are the weather predictions for tomorrow in London?
    jsonResponseSchema: |
        {
            "type": "object",
            "properties": {
                "predictions": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "properties": {
                            "content": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
```

See also [Structured Output doc](https://ai.google.dev/gemini-api/docs/structured-output) on Gemini API.
